server:
  port: '@server.port@'
  rest:
    port: '@server.rest.port@'

spring:
  application:
    name: '@project.name@'
  output:
    ansi:
      enabled: always
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/gambit
    username: postgres
    password: postgres
    hikari:
      idle-timeout: 30000
      maximum-pool-size: 10
      data-source-properties:
        reWriteBatchedInserts: true
  flyway:
    schemas: gbt

management:
  security:
    flag: false
  server:
    port: '@management.port@'
  metrics:
    tags:
      application: '@project.name@'
    export:
      prometheus:
        enabled: true
  endpoint:
    health:
      show-details: always
    metrics:
      enabled: true
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health,info,prometheus


info:
  version: '@project.version@'
  stage: dev
